# Generated by Django 5.2.17 on 2026-08-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('APPLE', 'Apple')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('agreed_terms_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
