# Generated by Django 5.2.17 on 2026-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="nickname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
