# Generated by Django 5.2.17 on 2026-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_member_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="language",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
