# Generated by Django 5.2.17 on 2026-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_member_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="provider",
            field=models.CharField(
                choices=[("GOOGLE", "Google"), ("KAKAO", "Kakao")], max_length=10
            ),
        ),
    ]
