# Generated by Django 5.2.17 on 2026-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_member_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
