# Generated by Django 5.2.17 on 2026-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
    ]
