# Generated by Django 5.2.17 on 2026-08-20 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('places', '0006_placetranslation_is_approved_placetranslation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.member')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESTAURANT', '식당'), ('CAFE', '카페'), ('OTHER', '그 외')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('road_address_name', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('kakao_place_id', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_places', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'role')},
            },
        ),
    ]
