# Generated by Django 5.2.17 on 2026-08-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="place",
            name="source",
        ),
        migrations.RemoveField(
            model_name="place",
            name="source_id",
        ),
        migrations.CreateModel(
            name="PlaceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=100)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
