# Generated by Django 5.2.17 on 2026-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_place_unique_together_remove_place_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placesource",
            name="source_id",
            field=models.CharField(max_length=500),
        ),
    ]
