# Generated by Django 5.2.17 on 2026-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetranslation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placetranslation',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='placetranslation',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktranslation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worktranslation',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='worktranslation',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
