# Generated by Django 5.2.17 on 2026-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "places",
            "0006_placetranslation_is_approved_placetranslation_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="etiquette",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="place",
            name="photo_tips",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="place",
            name="recommended_time",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
