# Generated by Django 5.2.17 on 2026-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_place_etiquette_place_photo_tips_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placetranslation",
            name="language",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="worktranslation",
            name="language",
            field=models.CharField(max_length=35),
        ),
    ]
