# Generated by Django 5.2.17 on 2026-09-06 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_work_title_key_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=500)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="places.work",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
