# Generated by Django 5.2.17 on 2026-09-07 13:49

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_worksource"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="place_name_upper_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="placetranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="placetrans_name_upper_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="work_title_upper_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="worktranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="worktrans_title_upper_trgm",
            ),
        ),
    ]
