# Generated by Django 5.2.17 on 2026-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_place_place_name_upper_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="work",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
