# Generated by Django 5.2.17 on 2026-09-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0013_alter_place_photo_url_alter_work_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
