# Generated by Django 5.2.17 on 2026-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0013_alter_place_photo_url_alter_work_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="photo_credit",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
