# Generated by Django 5.2.17 on 2026-09-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0014_work_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="runtime",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
