# Generated by Django 5.2.17 on 2026-09-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0015_work_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="genre",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
