# Generated by Django 5.2.17 on 2026-09-19 09:31

from django.db import migrations, models

from places.regions import extract_region


def fill_region(apps, schema_editor):
    """이미 있는 명소들의 시/도를 주소에서 계산해 채운다.

    migrate만 하면 로컬·배포 DB 모두 자동으로 채워진다.
    bulk_update는 Place.save()나 저장 신호를 거치지 않으므로 번역이 다시 걸리지 않는다.
    """
    Place = apps.get_model("places", "Place")
    places = list(Place.objects.only("id", "address", "region"))
    for place in places:
        place.region = extract_region(place.address)
    Place.objects.bulk_update(places, ["region"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0016_work_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="region",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=20
            ),
        ),
        migrations.RunPython(fill_region, migrations.RunPython.noop),
    ]
