# Generated by Django 5.2.17 on 2026-08-20 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('favorites', '0001_initial'),
        ('places', '0006_placetranslation_is_approved_placetranslation_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('member', 'place')},
        ),
        migrations.AddField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.place'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('member', 'course'), ('member', 'place')},
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('place__isnull', False), ('course__isnull', True)), models.Q(('place__isnull', True), ('course__isnull', False)), _connector='OR'), name='favorite_exactly_one_of_place_or_course'),
        ),
    ]
