# Generated by Django 5.2.17 on 2026-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(max_length=500),
        ),
    ]
