# Generated by Django 5.2.17 on 2026-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="language",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="reviewtranslation",
            name="language",
            field=models.CharField(max_length=35),
        ),
    ]
