# Generated by Django 5.2.17 on 2026-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewphoto",
            name="photo_url",
            field=models.URLField(max_length=500),
        ),
    ]
