# Generated by Django 5.2.17 on 2026-09-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0016_work_genre"),
        ("reviews", "0004_alter_reviewphoto_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="works",
            field=models.ManyToManyField(
                blank=True, related_name="reviews", to="places.work"
            ),
        ),
    ]
