"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일(git에 안 올라감)에 적어둔 값을 환경변수로 읽어들인다.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 운영에서는 Render 환경변수 DJANGO_SECRET_KEY로 넣는다. 없으면 로컬 개발용 기본값을 쓴다.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-6z_d3ch2my5^7ef)+(4eznx!z@mjl^1q7d0m0=oh4tb)29hmd2",
)

# SECURITY WARNING: don't run with debug turned on in production!
# 운영에서는 Render 환경변수 DJANGO_DEBUG=False로 끈다. 기본값은 로컬 개발용 True.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

# 접속을 허용할 호스트(도메인) 목록.
# Render는 배포된 주소를 RENDER_EXTERNAL_HOSTNAME 환경변수로 자동으로 넣어준다.
# 그 외에 더 허용할 도메인이 있으면 DJANGO_ALLOWED_HOSTS에 쉼표로 구분해 넣는다.
ALLOWED_HOSTS: list[str] = []
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
_extra_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(",") if h.strip()]

# Render는 HTTPS를 앞단 프록시에서 끝내고 뒤로는 http로 전달한다.
# 이 헤더를 봐야 Django가 원래 HTTPS 요청이었음을 알 수 있다.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 관리자 로그인 등 POST 요청의 CSRF 검증에서 신뢰할 출처(운영 도메인).
CSRF_TRUSTED_ORIGINS: list[str] = []
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")

# 운영(DEBUG=False)에서만 켜는 HTTPS 보안 설정.
# 로컬 개발은 http라서 켜면 접속이 막히므로 DEBUG일 때는 건드리지 않는다.
if not DEBUG:
    # http로 들어온 요청을 https로 자동 리다이렉트한다.
    SECURE_SSL_REDIRECT = True
    # 세션 쿠키(주로 admin 로그인)를 https 연결에서만 주고받는다.
    SESSION_COOKIE_SECURE = True
    # CSRF 쿠키도 https 전용으로 제한한다.
    CSRF_COOKIE_SECURE = True
    # 브라우저에게 "앞으로 이 도메인은 https로만 접속하라"고 기억시킨다(HSTS).
    # 처음엔 1시간(3600초)으로 짧게 두고, 문제 없으면 나중에 늘린다.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 유사 검색(trigram_similar, TrigramSimilarity)에 필요 — PostgreSQL 전용 조회 기능
    "django.contrib.postgres",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "accounts",
    "places",
    "main",
    "reviews",
    "favorites",
    "courses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # 정적 파일(admin CSS 등)을 Django가 직접 서빙하게 해준다. SecurityMiddleware 바로 뒤에 둔다.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "aftertaste"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# Render의 PostgreSQL은 접속정보를 DATABASE_URL 하나로 준다.
# 이 값이 있으면 위 개별 설정 대신 그걸 파싱해서 쓴다(로컬은 그대로 개별 설정 사용).
if os.environ.get("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(
        default=os.environ["DATABASE_URL"],
        conn_max_age=600,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
# collectstatic이 정적 파일을 한곳에 모으는 위치. Render 빌드 단계에서 collectstatic을 실행한다.
STATIC_ROOT = BASE_DIR / "staticfiles"

# whitenoise: 정적 파일을 압축하고 파일명에 해시를 붙여 저장한다(캐싱에 유리).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]
# 배포된 프론트엔드 주소는 CORS_ALLOWED_ORIGINS 환경변수에 쉼표로 구분해 넣는다.
_extra_cors = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if _extra_cors:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(",") if o.strip()]


# 외부 공공데이터 API 키
# 실제 호출 코드는 places/sources/ 아래에 있다 (docs/DETAIL_SPEC.md 7장 참고).
# 한국문화정보원(KCISA)은 API가 아니라 CSV 파일로만 제공돼서 키가 필요 없지만,
# 나중에 API가 열릴 수도 있어서 자리는 남겨둔다.
KOBIS_API_KEY = os.environ.get("KOBIS_API_KEY", "")
GYEONGGI_DATA_DREAM_API_KEY = os.environ.get("GYEONGGI_DATA_DREAM_API_KEY", "")
KCISA_API_KEY = os.environ.get("KCISA_API_KEY", "")

# 카카오맵 지오코딩용 REST API 키. 좌표가 없는 출처(경기 데이터 드림)의 장소명을
# 좌표로 바꿔서, 좌표가 있는 다른 출처(한국문화정보원)와 같은 명소인지 비교하는 데 쓴다.
KAKAO_API_KEY = os.environ.get("KAKAO_API_KEY", "")

# Google Cloud Translation API (v2) 키. 명소·작품 번역에 쓴다 (docs/DETAIL_SPEC.md 6-1 #13).
GOOGLE_TRANSLATE_API_KEY = os.environ.get("GOOGLE_TRANSLATE_API_KEY", "")

# 한국영상자료원 KMDB(한국영화데이터베이스) Open API 키. 영화(Work) 정보를 채운다 (docs/DETAIL_SPEC.md 6-1 #28).
KMDB_API_KEY = os.environ.get("KMDB_API_KEY", "")

# TMDB(The Movie Database) API 읽기 액세스 토큰(v4). 드라마를 비롯해 KMDB로 못 채운
# 작품의 줄거리·감독·방영일자·포스터를 보강하는 데 쓴다. KMDB는 드라마를 거의 안 담고
# KOBIS는 포스터를 안 줘서, 드라마는 TMDB로 보강한다 (docs/DETAIL_SPEC.md 6-1 #29).
# "Bearer <토큰>" 헤더로 호출한다 (짧은 v3 api_key 문자열이 아니다).
TMDB_API_KEY = os.environ.get("TMDB_API_KEY", "")

# TMDB 포스터 이미지 CDN. poster_path 앞에 붙여서 완전한 URL을 만든다.
# 크기 목록: w92 / w154 / w185 / w342 / w500 / w780 / original.
TMDB_IMAGE_BASE_URL = os.environ.get("TMDB_IMAGE_BASE_URL", "https://image.tmdb.org/t/p")
TMDB_POSTER_SIZE = os.environ.get("TMDB_POSTER_SIZE", "w500")


# Firebase Authentication
# 서비스 계정 키 파일 경로. 아직 준비되지 않았다면 파일이 없어도 서버는 정상 부팅되고,
# 실제로 토큰을 검증하려는 시점에만 에러가 난다 (accounts/firebase.py 참고).
FIREBASE_CREDENTIALS_PATH = os.environ.get(
    "FIREBASE_CREDENTIALS_PATH", str(BASE_DIR / "firebase-service-account.json")
)


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.FirebaseAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "EXCEPTION_HANDLER": "accounts.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular (Swagger/OpenAPI 문서)
# https://drf-spectacular.readthedocs.io/
SPECTACULAR_SETTINGS = {
    "TITLE": "Aftertaste API",
    "DESCRIPTION": "촬영 명소 추천 서비스 백엔드 API",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
